### ISSUE TITLE
Should the fix preview look more like what elm-format would produce?

### ISSUE THREAD

**Issue by r-k-b** [r-k-b/no-long-import-lines#10]
Currently, the easy fix to make is inserting a newline before the closing parenthesis, and elm-format will do the heavy lifting of breaking the items within to individual lines. But, the preview doesn't suggest that:

![image](https://user-images.githubusercontent.com/2717397/104090129-91eb8400-52c8-11eb-8dd1-72c50c334b06.png)

Should the preview look more like what elm-format would produce?

These wide lines will typically become many long lines, will that be presentable in the preview?

<details>
    <summary>(The example becomes 23 lines high)</summary>

A mockup:

```
-- ELM-REVIEW ERROR ----------------------------------- app/DefaultData.elm:24:1

NoLongImportLines: Do not keep `import` lines longer than 120 characters.

23| import Set
24| import Types exposing (Action, ActionOutcome(..), Agent, Consideration, ConsiderationInput(..), Fire, FireExtinguisher, Food, GeneratorType(..), Growable, GrowableState(..), Hitpoints(..), Holding(..), InputFunction(..), Portable(..), Range(..), ReferenceToPortable(..), Signal(..), Species(..), YDownCoords)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
25| import Vector2d

Even though `elm-format` keeps the items sorted, having very long lines like
this invites merge conflicts, and reduces readability.

I think I can fix this. Here is my proposal:

 23| import Set
 24| import Types exposing (Action, ActionOutcome(..), Agent, Consideration, ConsiderationInput(..), Fire, FireExtinguisher, Food, GeneratorType(..), Growable, GrowableState(..), Hitpoints(..), Holding(..), InputFunction(..), Portable(..), Range(..), ReferenceToPortable(..), Signal(..), Species(..), YDownCoords)
 25| import Types
 26|     exposing
 27|         ( Action
 28|         , ActionOutcome(..)
 29|         , Agent
 30|         , Consideration
 31|         , ConsiderationInput(..)
 32|         , Fire
 33|         , FireExtinguisher
 34|         , Food
 35|         , GeneratorType(..)
 36|         , Growable
 37|         , GrowableState(..)
 38|         , Hitpoints(..)
 39|         , Holding(..)
 40|         , InputFunction(..)
 41|         , Portable(..)
 42|         , Range(..)
 43|         , ReferenceToPortable(..)
 44|         , Signal(..)
 45|         , Species(..)
 46|         , YDownCoords
 47|         )
 48| import Vector2d

? Do you wish to apply this fix? › (Y/n)
```
</details>

Do I need to dive into the nodes and apply that whitespace in the fix, or can I leverage elm-format for the preview somehow?

**Comment by jfmengels** [comment]
> Should the preview look more like what elm-format would produce?

I think that would be better. At the moment the fix works but it's a bit confusing what it does, especially if you don't know that `elm-format` will run afterwards or don't know `elm-format` that well.

> can I leverage elm-format for the preview somehow?

Unfortunately, no. Everything until the point of showing the error to to the user needs to be a single `Elm` call, but `elm-format` would require some async steps, which doesn't work for `elm-review` (and wouldn't be available in `elm-test` tests`.

My thinking is that instead of adding whitespace for every imported element, you can overwrite whatever comes after and including `exposing` and format all that just like `elm-format` would do it. That would be the better solution I think.
